# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:9

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/

before_script:
  - yarn install

test:
  script:
    - yarn test:unit --coverage --no-color
  coverage: '/All files\s*\|\s*([\d\.]+)/'

build:
  script:
    - yarn build
